{% set version = "1.5-3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fracdiff
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fracdiff_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fracdiff/fracdiff_{{ version }}.tar.gz
  sha256: 0f90946b4092feff93fad094a2c91bb47c8051595210e86c029c70238dbf7fc0

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ compiler('fortran') }}  # [osx and arm64]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - libblas
  run:
    - r-base

test:
  commands:
    - $R -e "library('fracdiff')"           # [not win]
    - "\"%R%\" -e \"library('fracdiff')\""  # [win]

about:
  home: https://github.com/mmaechler/fracdiff
  license: GPL-2.0-or-later
  summary: Maximum likelihood estimation of the parameters of a fractionally differenced ARIMA(p,d,q) model (Haslett and Raftery, Appl.Statistics, 1989); including inference and basic methods.  Some alternative algorithms to estimate "H".
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
