{% set version = "1.5-3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fracdiff
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fracdiff_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fracdiff/fracdiff_{{ version }}.tar.gz
  sha256: 0f90946b4092feff93fad094a2c91bb47c8051595210e86c029c70238dbf7fc0

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - libblas
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('fracdiff')"           # [not win]
    - "\"%R%\" -e \"library('fracdiff')\""  # [win]

about:
  home: https://github.com/mmaechler/fracdiff
  license: GPL-2.0-or-later
  summary: Maximum likelihood estimation of the parameters of a fractionally differenced ARIMA(p,d,q) model (Haslett and Raftery, Appl.Statistics, 1989); including inference and basic methods.  Some alternative algorithms to estimate "H".
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: fracdiff
# Version: 1.5-0
# VersionNote: Released 1.4-2 on 2012-12-01 on CRAN
# Date: 2019-12-09
# Title: Fractionally Differenced ARIMA aka ARFIMA(P,d,q) Models
# Authors@R: c(person("Martin","Maechler", role=c("aut","cre"), email="maechler@stat.math.ethz.ch", comment = c(ORCID = "0000-0002-8685-9910")) , person("Chris", "Fraley", role=c("ctb","cph"), comment = "S original; Fortran code") , person("Friedrich", "Leisch", role = "ctb", comment = c("R port", ORCID = "0000-0001-7278-1983")) , person("Valderio", "Reisen", role="ctb", comment = "fdGPH() & fdSperio()") , person("Artur",  "Lemonte",  role="ctb", comment = "fdGPH() & fdSperio()") , person("Rob", "Hyndman", email="Rob.Hyndman@monash.edu", role="ctb", comment = c("residuals() & fitted()", ORCID = "0000-0002-2140-5352")) )
# Description: Maximum likelihood estimation of the parameters of a fractionally differenced ARIMA(p,d,q) model (Haslett and Raftery, Appl.Statistics, 1989); including inference and basic methods.  Some alternative algorithms to estimate "H".
# Imports: stats
# Suggests: longmemo, forecast, urca
# License: GPL (>= 2)
# URL: https://github.com/mmaechler/fracdiff
# BugReports: https://github.com/mmaechler/fracdiff/issues
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2019-12-09 10:23:55 UTC; maechler
# Author: Martin Maechler [aut, cre] (<https://orcid.org/0000-0002-8685-9910>), Chris Fraley [ctb, cph] (S original; Fortran code), Friedrich Leisch [ctb] (R port, <https://orcid.org/0000-0001-7278-1983>), Valderio Reisen [ctb] (fdGPH() & fdSperio()), Artur Lemonte [ctb] (fdGPH() & fdSperio()), Rob Hyndman [ctb] (residuals() & fitted(), <https://orcid.org/0000-0002-2140-5352>)
# Maintainer: Martin Maechler <maechler@stat.math.ethz.ch>
# Repository: CRAN
# Date/Publication: 2019-12-09 15:00:02 UTC
