appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: rjKEQYj9DBJizd+nx40bo/c4YKd3ChQD7228HfFN2DaV5v1KaDQ4A2WNGFrmRDoAYy6WLVhHOGtecJo+D0WA/qlfaakVOuyKPXj5CBOmQX44NXrlqbUw7mq6lmIFDE9fAt/OdpMPOCSeTKhSpdHXGaFw2McTpnMYJPEEoSxzBs1riiFdSh5XliGAO0Sta82l87ypzJKbP/rhjUfiUzXE3UVvXLiceA8VCP0nZj8/OVUWy9ras8ZdWbwDqCqxh3y/CD/4qTtCDzr1RKlIr+xFzOEnaoEVFMgv388qByP6KjsDW0qSmkfNr/zRxP4Hyuvc0NKXAXjIFbVBzzSnrRcfuv6XV7ucuFHvlUXFj3VRSZn3qAlJTBQG2tOcVDSTnknUYKBHg7UHc4e6xaVrP2iV2PalIQWJdcztYUy0EN5myHpRgb4Y/dAY0DkXGOvN0/9fq6IEk5VlZN7zt4JSKIrIBD1TK/sprD201Js1uZwrGW3JNxrLuY2/0TASM+pu8Zy4UoLFBNNFDdyfyjgf5KsdvMEVj+q3EsKuFbpB3hDuBI/kpMAg2XsAJAPzxiKFJRLvVgAWgBCRbAaTOPFlWiyfzX4Hd0ec1Ek1zby1R691Cn85P8lEL4copnM9On+lmk4BexyFikKVP2XnGw5TJiPDGGR6tzad/mgCuIveJC38jq8=}
bot:
  automerge: true
